### ISSUE TITLE
Does api-url always correspond to https://api.github.com/repos/owner_name/project_name?

### ISSUE THREAD

**Issue by wolfenmark** [seart-group/ghs#13]
Hi,
the api-url link can be reconstructed from the project 'owner_name/project_name'.

The typical link format is something like:
https://api.github.com/repos/owner_name/project_name

What happens when owner changes?
Can this disambiguate repos stored in your dataset with older names by seeing that the api-url points to a different link?

I'm not sure how (or how many times) GitHub can redirect some repos searched by the older name to the new owner/repo name. This is more a possible investigation to ensure consistency in the output.

**Comment by emadpres** [comment]
I guess when a repo is renamed or the ownership is moved, the old data of the repo will remain in the dataset and later when the repo gets updated under new name/ownership we add a new entry inside our dataset. I guess when we implement #14 this issue will be automatically solved. So I close this issue as it's related to #14.
