### ISSUE TITLE
docker deploy error: when RUN mvn -e --no-transfer-progress clean install -am -DskipTests 

### ISSUE THREAD

**Issue by heurainbow** [seart-group/ghs#236]
docker deploy error: when RUN mvn -e --no-transfer-progress clean install -am -DskipTests 

Better to have pre-built docker image on dockerhub or somewhere else.
![image](https://github.com/seart-group/ghs/assets/6753276/363b8856-aa5e-4d9d-8a43-ed5dbe88f236)

**Comment by dabico** [comment]
Hi @heurainbow 

Thank you for the report. I will introduce some GitHub workflows to publish image builds to Docker Hub. However, your build failure is likely due to a network issue, so I would look into that to make it work until then.

**Comment by dabico** [comment]
> Thanks.
> 
> Please add a subsection to use pre-built image by docker pull. FYI, images on dockerhub have no default tag latest , which is not convenient.

This has been implemented now. Note that instead of the antiquated `gse-` prefix, we have opted to replace it with `ghs-`. Here's a full list of available tags:

https://hub.docker.com/r/seart/ghs-server/tags
