### ISSUE TITLE
Gateway Time-Out

### ISSUE THREAD

**Issue by kargaranamir** [seart-group/ghs#29]
**What's heppening?**
Hi, when i use the [web interface](seart-ghs.si.usi.ch/) without any filter to save the result it gives me "504 Gateway Time-Out error".

**How to see the problem again?**
Open [web interface](seart-ghs.si.usi.ch/) without choosing anything just clike on Search button and then clicke on Download CSV.

**Output Result:**
Generated url:
```
https://seart-ghs.si.usi.ch/api/r/download/csv?hasWiki=false&onlyForks=false&hasLicense=false&nameEquals=false&hasPulls=false&excludeForks=false&hasIssues=false
```
<img width="409" alt="Screen Shot 2022-10-24 at 2 52 58 PM" src="https://user-images.githubusercontent.com/26163093/197531066-6fb25213-fde1-4402-bd81-f77076f8cefc.png">

Btw. Can you share the whole up-to-date dataset? I found a dataset on [zenodo](https://zenodo.org/record/4588464#.Y1VWpuzP2eA), but it is not up-to-date

**Comment by emadpres** [comment]
Thank you @kargaranamir for reporting the issue. I can confirm this issue by replicating it on my machine.
It occurs ~60 seconds after the "Preparing Your Download ..." message is shown.

**Comment by dabico** [comment]
Hi @kargaranamir 

Thank you for bringing this to our attention. Judging by the information provided, I think this is an issue with our nginx configuration. The time needed to create the large dataset you requested takes longer than nginx allows. Goes without saying that we will investigate this further.

**Comment by dabico** [comment]
@kargaranamir I've fixed the issue, you can now download our entire database in any format. Keep in mind that as before it can take up to 30 secs (depending on the query) for the server to actually start streaming the file.
