### ISSUE TITLE
Total Issues and Total Pull Reqs null instead of 0

### ISSUE THREAD

**Issue by marodev** [seart-group/ghs#5]
Values for '**Total Issues**' and '**Total Pull Reqs**' are sometimes 'null' instead of 0.

For example:
![image](https://user-images.githubusercontent.com/23633010/109625188-4ffbf300-7b3f-11eb-9984-09a70901a820.png)

Link to GitHub repo:
https://github.com/0xc0000054/pdn-gmic

Here are some correct examples:

![image](https://user-images.githubusercontent.com/23633010/109625778-0233ba80-7b40-11eb-8b96-d6ea5f65bfc2.png)

![image](https://user-images.githubusercontent.com/23633010/109625897-2a231e00-7b40-11eb-91d2-bf113183de50.png)

![image](https://user-images.githubusercontent.com/23633010/109626212-8d14b500-7b40-11eb-9243-5f0be49494cd.png)

**Comment by emadpres** [comment]
Thank you @marodev for bringing up the issues. As of now, we are collecting part of the data by crawling GitHub webpages. This method is prone to a variety of errors, especially when GitHub decides to alter a page's structure.

To solve such issues, we are working on a new way of collecting such information relying only on GitHub APIs and probably we will deploy it by end of this week.

**Comment by marodev** [comment]
Thank you for the fast feedback. Great, I'm looking forward to it!

**Comment by emadpres** [comment]
Note: though commit 47b2cf0 fixes this issue with a new mining algorithm, the repositories info will be updated only when the repo gets updated (e.g., have a new commit).
