### ISSUE TITLE
Update all the `README` files

### ISSUE THREAD

**Issue by dabico** [seart-group/ghs#50]
Given that the project has seen significant changes in terms of how it is set up and run, we should update all the documentation in preparation for the next release.

**Comment by AlbertCerfeda** [comment]
👍🏻

**Comment by dabico** [comment]
@AlbertCerfeda can you please update the documentation to include the changes you introduced? This primarily concerns the `application.properties` arguments that you added.

**Comment by dabico** [comment]
Reminder @AlbertCerfeda
