### ISSUE TITLE
Incorrect search results when searching by Language

### ISSUE THREAD

**Issue by dabico** [seart-group/ghs#69]
The new querying functionalities you introduced in #45 have caused unintended issues: When searching _only_ by language without specifying metrics, only repositories with calculated metrics are matched. You have to ensure that joins to `git_repo_metric` are only performed if _both_ a language and a metric filter are specified. I also recommend refactoring the `GitRepoSpecification` to accept a new `GitRepoSearch` object instead of a `Map<String, ?>`. This intermediate representation will be derived from its `DTO` counterpart. It will contain all the information that is otherwise present in the map, along with boolean methods that will be used during the construction of the specification. In fact, why not go a step further and implement a conversion chain that goes: `GitRepoSearchDTO` -> `GitRepoSearch` -> `GitRepoSpecification`.

**Comment by dabico** [comment]
There is another oversight that I want you to fix:

https://github.com/seart-group/ghs/blob/0fc8e64d3967fb49a3a059ea23f2708ac34fa089/src/main/java/usi/si/seart/repository/specification/GitRepoSpecification.java#L148-L153

You are using the `lower` instead of the `upper` endpoint on line 152.

**Comment by AlbertCerfeda** [comment]
> The new querying functionalities you introduced in #45 have caused unintended issues: When searching _only_ by language without specifying metrics, only repositories with calculated metrics are matched. You have to ensure that joins to `git_repo_metric` are only performed if _both_ a language and a metric filter are specified. I also recommend refactoring the `GitRepoSpecification` to accept a new `GitRepoSearch` object instead of a `Map<String, ?>`. This intermediate representation will be derived from its `DTO` counterpart. It will contain all the information that is otherwise present in the map, along with boolean methods that will be used during the construction of the specification. In fact, why not go a step further and implement a conversion chain that goes: `GitRepoSearchDTO` -> `GitRepoSearch` -> `GitRepoSpecification`.

I understand the usefulness of a `GitRepoSearchDTO` class, but why have also the `GitRepoSearch` class ? It seems a little bit redundant to me. Of course I could store some boolean attributes in it like whether metric filters have upper/lower endpoints, but I feel like it would be a minor advantage compared to just checking conditions directly in `GitRepoSpecification` like before.

**Comment by dabico** [comment]
Fixed in #70
